#!/usr/bin/env python3

# TODO license
import argparse
import os
from getpass import getpass

from p2kp2 import PassReader, P2KP2, DbAlreadyExistsException


def exec_normal_mode(args):
    """Interactive script."""
    # Intro message and warnings
    intro = "Welcome! pass2keepass2 will convert your pass database into a keepass2 one.\n\n" \
            "> WARNING < This script DOES NOT try to be memory secure: your password will NOT be " \
            "encrypted while in memory, so you probably want to execute this on a trusted hardware.\n\n" \
            "The script will now read your input password-store, so you will probably be asked to " \
            "unlock it.\nKeep in mind this may take a while, depending on the number of entries.\n\n" \
            "Input password-store: {}\n" \
            "Output keepass2 database: {}\n" \
        .format(os.path.abspath(args.input) if args.input is not None else os.path.expanduser("~/.password-store"),
                os.path.abspath(args.output) if args.output is not None else os.path.abspath("pass.kdbx"))
    print(intro)
    answer = input("Are you ready to proceed? [Y/n] ")
    if not (answer.lower() == "y" or answer.lower() == ""):
        print("Ok, bye!")
        exit(1)

    # Read the pass db
    print("\n... Loading ...\n")
    reader = PassReader(path=args.input)
    reader.parse_db()
    print("Password-store decrypted! {} entries are ready to be converted.".format(len(reader.entries)))

    # Choose a password for keepass
    print("Now choose a strong password for your new keepass database!\n")
    password = None
    while password is None:
        p1 = getpass("A strong password: ")
        p2 = getpass("Enter it again! ")
        if p1 == p2:
            password = p1
        else:
            print("\n >>> Entered passwords do not match, try again.\n")

    # Write the keepass db
    print("Alright! It's finally time to write the keepass db. Hold tight, this might take a while!")
    print("\n... Loading ...\n")
    try:
        p2kp2 = P2KP2(password=password, destination=args.output, overwrite=args.force_overwrite)
    except DbAlreadyExistsException:
        print(">> ERROR: keepass database file already exists! "
              "Use -f if you want to force overwriting.")
        exit(1)
    p2kp2.populate_db(reader)
    print(
        "ALL DONE! {} entries have been added to the new keepass database!\nHave a nice day!"
        .format(len(p2kp2.db.entries))
    )


def exec_quick_mode(args):
    """More automated script"""
    print("Insert the password that will be used for decrypting the pass "
          "store and encrypting the new keepass db:")
    password = getpass("-> ")
    reader = PassReader(path=args.input, password=password)
    print("Reading password-store...", end=" ", flush=True)
    reader.parse_db()
    print("DONE")
    print("Writing keepass database...", end=" ", flush=True)
    try:
        p2kp2 = P2KP2(password=password, destination=args.output, overwrite=args.force_overwrite)
    except DbAlreadyExistsException:
        print("ERR!")
        print("\n>> ERROR: keepass database file already exists! "
              "Use -f if you want to force overwriting.")
        exit(1)

    p2kp2.populate_db(reader)
    print("ALL DONE! {} entries converted! Bye!".format(len(p2kp2.db.entries)))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', default=None)
    parser.add_argument('-o', '--output', default=None)
    parser.add_argument('-q', '--quick', action='store_true')
    parser.add_argument('-f', '--force-overwrite', action='store_true')
    parsed_args = parser.parse_args()

    if parsed_args.quick:
        exec_quick_mode(parsed_args)
    else:
        exec_normal_mode(parsed_args)

