---
name: prod

on:

  pull_request:
    branches:
      - "master"

  push:
    branches:
      - "master"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:

  ci:
    name: ci
    runs-on: ubuntu-latest
    env:
      using_act: ${{ github.actor == 'nektos/act'}}
      is_cron: ${{ github.event_name == 'schedule' }}

    steps:

      - name: Checkout.
        uses: actions/checkout@v2

      - name: Import test gpg keys.
        run: |
          gpg --import tests/keys/pass2keepass2_sec.gpg
          echo pass2keepass2 | gpg --import --batch --yes --passphrase-fd 0 tests/keys/pass2keepass2withpass_sec.gpg 

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - name: Make sure path are there also for act shells.
        if: env.using_act == 'true'
        run: |
          echo "export PATH=\"/opt/hostedtoolcache/Python/${{ env.python_version }}/x64:/opt/hostedtoolcache/Python/${{ env.python_version }}/x64/bin:$PATH\"" >> /root/.bashrc
          ln -s /usr/bin/gpg /usr/bin/gpg2

      - name: Upgrade pip.
        run: python -m pip install --upgrade pip

      - name: Install pipenv and invoke.
        run: pip install pipenv invoke

      - name: Install the project.
        run: pipenv install --dev

      - name: Launch tests.
        run: inv test

